[settings]
# tools can read the versions files used by other version managers
# for example, .nvmrc in the case of node's nvm
idiomatic_version_file_enable_tools = ['node', 'ruby']

[tools]
node = "24"
# rust = "1.82"
# ruby = "3"
# python = "3.12"
# go = "1.22"
